######################################################
# Update /etc/hosts file
# We need separate task for this, because this task
# can be run independently of configuration tasks
######################################################

---
# From https://gist.github.com/rothgar/8793800
- name: Update /etc/hosts file
  template: src=hosts.j2 dest=/etc/hosts
