#
# Common tasks to be run on the entire architecture
# Configuration tasks
#

---

- include: ssh.yml
- include: apt.yml
- include: hosts.yml

- name: Create shared Folder
  file: path=/shared state=directory owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }}
