#
# Configure SSH config and keys on nodes
#

---

- name: Copy hosts private key
  copy: src=insecure_key dest=~/.ssh/id_rsa force=yes mode=0600
  become: false

- name: Copy containers private key
  copy: src=container_key dest=~/.ssh/container_key force=yes mode=0600
  become: false

- name: Copy insecure key pub to authorized key
  become: false
  authorized_key: user={{ ansible_ssh_user }} key={{ lookup('file', 'insecure_key.pub') }}

- name: Configure SSH hosts config
  become: false
  template: src=ssh_config.j2 dest=~/.ssh/config force=yes

