---
# Configure all nodes
#- hosts: all
  #become: true  # allow priviledge escalation
  #roles:
    #- common


# Specific to master node
- hosts: "{{ master_hosts_group  }}"
  become: true
  roles:
    - nginx
    - redis
    - postgresql
    - hemeweb_master


# Specific to worker nodes
- hosts: "{{ worker_hosts_group }}"
  become: true
  vars:
    master_ip: "{{ hostvars[groups[master_hosts_group][0]][ preferred_ansible_interface ]['address'] }}"
  roles:
    - hemeweb_worker
