#
# Configure HemeWeb web application
#

---


- name: Install pip
  apt: name=python-pip state=latest

- name: Install python header
  apt: name=python-dev state=latest

- name: Install virtualenv
  become: true
  command: pip install virtualenv

- name: Clone hemeweb source code
  git: clone=true accept_hostkey=yes repo=https://github.com/SeiryuZ/HemeWeb.git
       update=true dest=/var/www/hemeweb


- name: Create virtualenv
  pip: virtualenv=/var/www/hemeweb/virtualenv virtualenv_python=python2
       requirements=/var/www/hemeweb/src/requirements.txt

- name: Copy settings_local
  copy: remote_src=True src=/var/www/hemeweb/src/local_settings.py.template
        dest=/var/www/hemeweb/src/local_settings.py force=False

- name: Update settings_local
  template: force=True src=local_settings.j2 dest=/var/www/hemeweb/src/local_settings.py

- name: Migrate database
  shell: /var/www/hemeweb/virtualenv/bin/python /var/www/hemeweb/src/manage.py migrate

- name: Collect static files
  shell: /var/www/hemeweb/virtualenv/bin/python /var/www/hemeweb/src/manage.py collectstatic -l --no-input


- name: Create super user
  shell: /var/www/hemeweb/virtualenv/bin/python /var/www/hemeweb/src/manage.py add_super_user --user=admin --password=admin --email=admin@admin.com
  ignore_errors: True


# TODO: UNSAFE PERMISSION
- name: Create upstart script to run hemeweb
  template: force=True src=hemeweb.j2 dest=/etc/init/hemeweb.conf
  register: upstart_configuration

- name: Restart hemeweb app
  service: name=hemeweb state=restarted


# TODO: UNSAFE PERMISSION
- name: Create upstart script to run hemeweb_worker (RQworker)
  template: force=True src=hemeweb_worker.j2 dest=/etc/init/hemeweb_worker.conf


# TODO: Figure out how to restart the worker safely when there are running jobs
- name: Start hemeweb_worker app
  service: name=hemeweb_worker state=started
