#
# Configure HemeWeb web application
#

---
- name: Get home path
  become: false
  shell: echo $HOME
  register: home_path

- name: Install pip
  apt: name=python-pip state=latest

- name: Install python header
  apt: name=python-dev state=latest

- name: Install virtualenv
  become: true
  command: pip install virtualenv

- name: Clone hemeweb source code
  git: clone=true accept_hostkey=yes repo=https://github.com/SeiryuZ/HemeWeb.git
       update=true dest=/var/www/hemeweb


- name: Install hemeweb requirements
  pip:  virtualenv=/var/www/hemeweb/virtualenv virtualenv_python=python2  requirements={{ item }}
  with_items:
    - /var/www/hemeweb/src/requirements.txt
    - /var/www/hemeweb/deployment/requirements.txt

- name: Copy settings_local
  copy: remote_src=True src=/var/www/hemeweb/src/local_settings.py.template
        dest=/var/www/hemeweb/src/local_settings.py force=False

- name: Update settings_local
  template: force=True src=local_settings.j2 dest=/var/www/hemeweb/src/local_settings.py

- name: Migrate database
  shell: /var/www/hemeweb/virtualenv/bin/python /var/www/hemeweb/src/manage.py migrate

- name: Collect static files
  shell: /var/www/hemeweb/virtualenv/bin/python /var/www/hemeweb/src/manage.py collectstatic -l --no-input


- name: Create super user
  shell: /var/www/hemeweb/virtualenv/bin/python /var/www/hemeweb/src/manage.py add_super_user --user=admin --password=admin --email=admin@admin.com
  ignore_errors: True


- name: Create upstart script to run hemeweb
  template: force=True src=hemeweb.j2 dest=/etc/init/hemeweb.conf
  register: upstart_configuration

- name: Restart hemeweb app
  service: name=hemeweb state=restarted


- name: Create upstart script to run hemeweb_worker (RQworker)
  template: force=True src=hemeweb_worker.j2 dest=/etc/init/hemeweb_worker.conf

- name: Create upstart script to run hemeweb_worker2 (RQworker)
  template: force=True src=hemeweb_worker.j2 dest=/etc/init/hemeweb_worker2.conf


# TODO: Figure out how to restart the worker safely when there are running jobs
- name: Start hemeweb_worker app
  service: name=hemeweb_worker state=restarted

- name: Start hemeweb_worker2 app
  service: name=hemeweb_worker2 state=restarted



# Pre processing stuff
- name: Clone HemeLB source code
  git: clone=true accept_hostkey=yes repo=https://github.com/UCL/hemelb.git
       update=true dest=/var/src/hemelb


- name: Install necessary tools for pre-processing
  apt: name={{ item }} state=latest
  with_items:
    - libcgal-dev
    - libvtk5-dev
    - python-vtk
    - vmtk
    - python-wxtools
    - python-wxversion
    - swig

- name: Install HemeLB tools requirements
  pip:  virtualenv=/var/src/hemelb/virtualenv virtualenv_site_packages=yes virtualenv_python=python2 name={{ item }}
  with_items:
    - cython
    - numpy

- name: Install HemeLB tools into python path
  shell: chdir=/var/src/hemelb/Tools /var/src/hemelb/virtualenv/bin/python /var/src/hemelb/Tools/setup.py install

- name: Install HemeLB Setup tools into python path
  shell: chdir=/var/src/hemelb/Tools/setuptool /var/src/hemelb/virtualenv/bin/python /var/src/hemelb/Tools/setuptool/setup.py install

