
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    - region: eu-west-1
    - master_node_count: 1
    - worker_node_count: 0
    - master_instance_type: t2.medium
    - worker_instance_type: m4.xlarge

  tasks:

    - name: Create ssh security group
      ec2_group:
        name: ssh
        description: HemeWeb - Security group that allow SSH from public IP
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

    - name: Create web security group
      ec2_group:
        name: web
        description: HemeWeb - Security group that allow web traffic
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0

    - name: Provision master node
      ec2:
        region: "{{ region }}"
        image: ami-f95ef58a
        instance_type: "{{ master_instance_type }}"
        key_name: hemeweb
        groups:
          - default
          - ssh
          - web
        wait: true
        count_tag:
          name: master
        exact_count: "{{ master_node_count }}"
        instance_tags:
          name: master

    - name: Provision worker nodes
      ec2:
        region: "{{ region }}"
        image: ami-f95ef58a
        instance_type: "{{ worker_instance_type }}"
        key_name: hemeweb
        groups:
          - default
          - ssh
        wait: true
        count_tag:
          name: worker
        exact_count: "{{ worker_node_count }}"
        instance_tags:
          name: worker
