---

- hosts: "{{ master_hosts_group  }}"
  become: true
  vars:
    master_hosts_group: "tag_name_master"
    worker_hosts_group: "tag_name_worker"
    preferred_network_interface: "eth0"
    preferred_ansible_interface: "ansible_default_ipv4"
  roles:
    - hemeweb_master

