
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    - master_node_count: 1
    - worker_node_count: 2
    - master_instance_type: m4.large
    - worker_instance_type: m4.xlarge

  tasks:

    - name: Provision master node
      digital_ocean:
        name: master
        state: present
        command: droplet
        size_id: 8gb
        region_id: lon1
        image_id: ubuntu-14.04.4-x64
        private_networking: yes
        wait_timeout: 300

    # TODO: Loop these
    - name: Provision worker nodes
      digital_ocean:
        id: 1
        state: present
        command: droplet
        size_id: 8gb
        region_id: lon1
        image_id: ubuntu-14.04.4-x64
        private_networking: yes
        wait_timeout: 300

    - name: Provision worker nodes
      digital_ocean:
        id: 2
        state: present
        command: droplet
        size_id: 8gb
        region_id: lon1
        image_id: ubuntu-14.04.4-x64
        private_networking: yes
        wait_timeout: 300
