# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='configuration_file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='input_file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
