# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20160619_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(1, 'Added'), (2, 'Queued'), (3, 'Done'), (0, 'Failed')], default=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='configuration_file',
            field=models.FileField(upload_to=jobs.models.job_directory_path),
        ),
        migrations.AlterField(
            model_name='job',
            name='input_file',
            field=models.FileField(upload_to=jobs.models.job_directory_path),
        ),
    ]
