# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20160619_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='job',
            name='instance_type',
            field=models.IntegerField(default=1, verbose_name=((1, b'2 Cores'), (2, b'4 Cores'), (3, b'8 Cores'), (4, b'16 Cores'))),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(1, b'Added'), (2, b'Queued'), (10, b'Running'), (3, b'Done'), (0, b'Failed')], default=1),
        ),
    ]
