# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20160624_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='instance_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='instance_type',
            field=models.IntegerField(default=1, verbose_name=((2, b'2 Cores'), (4, b'4 Cores'), (8, b'8 Cores'), (16, b'16 Cores'))),
        ),
    ]
