# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 14:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20160624_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='container_image',
            field=models.IntegerField(choices=[(1, b'seiryuz/hemelb-core:0.0.2'), (2, b'seiryuz/hemelb-core:0.0.3')], default=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='configuration_file',
            field=models.FileField(upload_to=jobs.models.job_directory_path, verbose_name=b'Config (.xml)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='input_file',
            field=models.FileField(upload_to=jobs.models.job_directory_path, verbose_name=b'Input (.gmy)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='instance_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(36)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='instance_type',
            field=models.IntegerField(choices=[(2, b'2 Cores'), (4, b'4 Cores'), (8, b'8 Cores'), (16, b'16 Cores')], default=2),
        ),
    ]
