# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20160625_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='profile_file',
            field=models.FileField(blank=True, upload_to=jobs.models.job_directory_path, verbose_name=b'Profile file (.pr2)'),
        ),
        migrations.AddField(
            model_name='job',
            name='stl_file',
            field=models.FileField(blank=True, upload_to=jobs.models.job_directory_path, verbose_name=b'Geometry file (.stl)'),
        ),
    ]
