# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 17:28
from __future__ import unicode_literals

import core.fields
import django.core.validators
from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20160803_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='configuration_file',
            field=core.fields.ContentTypeRestrictedFileField(blank=True, upload_to=jobs.models.job_directory_path, verbose_name=b'HemeLB config file (.xml)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='container_image',
            field=models.IntegerField(choices=[(1, b'seiryuz/hemelb-core:0.0.2'), (2, b'seiryuz/hemelb-core:0.0.3')], default=1, verbose_name=b'HemeLB Version'),
        ),
        migrations.AlterField(
            model_name='job',
            name='input_file',
            field=core.fields.ContentTypeRestrictedFileField(blank=True, upload_to=jobs.models.job_directory_path, verbose_name=b'GMY geometry file (.gmy)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='instance_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(36)], verbose_name=b'How many machine'),
        ),
        migrations.AlterField(
            model_name='job',
            name='instance_type',
            field=models.IntegerField(choices=[(2, b'2 Cores'), (4, b'4 Cores'), (8, b'8 Cores'), (16, b'16 Cores'), (36, b'36 Cores')], default=2, verbose_name=b'Machine Type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='stl_file',
            field=core.fields.ContentTypeRestrictedFileField(blank=True, upload_to=jobs.models.job_directory_path, verbose_name=b'STL geometry file (.stl)'),
        ),
    ]
